language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - software-properties-common
      - python-software-properties
      - cmake

before_install:
  # gcc
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang
  - if [ "$CXX" == "clang++" ]; then sudo echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ]; then sudo echo "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list; fi

  - apt-get update

install:
  # gcc
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y g++-6; fi
  - if [ "$CXX" == "g++" ]; then sudo export CXX="g++-6"; fi

  # clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y clang++-3.9; fi
  - if [ "$CXX" == "clang++" ]; then sudo export CXX="clang++-3.9"; fi

script:
  - cmake .
  - make
  - ctest --verbose
