language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - g++-6
    sources:
      - ubuntu-toolchain-r-test
script:
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-6 .
  - make
  - ctest --verbose

